# Generated by Django 5.0 on 2024-01-18 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('videoflixbackend', '0003_remove_video_likes_video_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='liked_videos',
            field=models.ManyToManyField(related_name='liked_videos', to='videoflixbackend.video'),
        ),
    ]
