# Generated by Django 5.0 on 2024-04-06 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoflixbackend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='isVisible',
            field=models.BooleanField(default=False),
        ),
    ]
