# Generated by Django 5.0 on 2024-01-04 18:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoflixbackend', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='category',
            field=models.CharField(choices=[('allgemein', 'Allgemein'), ('kids', 'Kids'), ('funny', 'Funny'), ('noidea', 'Noidea')], default='allgemein', max_length=20),
        ),
        migrations.AddField(
            model_name='video',
            name='created_from',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
