# Generated by Django 5.0 on 2024-01-18 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoflixbackend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
