# Generated by Django 5.0 on 2024-02-07 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videoflixbackend', '0004_video_view_count'),
        ('videoflixbackend', '0008_alter_video_thumbnail'),
    ]

    operations = [
    ]
