# Generated by Django 5.0 on 2024-02-29 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoflixbackend', '0015_alter_video_thumbnail_alter_video_video_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoQuality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quality', models.CharField(max_length=20)),
                ('video_file', models.FileField(blank=True, null=True, upload_to='videos')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualities', to='videoflixbackend.video')),
            ],
        ),
    ]
