# Generated by Django 5.0 on 2024-03-06 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoflixbackend', '0016_videoquality'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='video',
            name='film_rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='video',
            name='origin',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
