# Generated by Django 5.0 on 2024-03-06 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoflixbackend', '0017_video_duration_video_film_rating_video_origin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='duration',
        ),
        migrations.AlterField(
            model_name='video',
            name='category',
            field=models.CharField(choices=[('allgemein', 'Allgemein'), ('kids', 'Kids'), ('funny', 'Funny'), ('noidea', 'Noidea'), ('action', 'Action'), ('drama', 'Drama'), ('fantasy', 'Fantasy'), ('horror', 'Horror'), ('comedy', 'Comedy'), ('krimi', 'Krimi'), ('thriller', 'Thriller'), ('science_fiction', 'Science Fiction')], default='allgemein', max_length=20),
        ),
    ]
