# Generated by Django 5.0 on 2024-03-06 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoflixbackend', '0018_remove_video_duration_alter_video_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='category',
            field=models.CharField(choices=[('allgemein', 'Allgemein'), ('kids', 'Kids'), ('funny', 'Funny'), ('noidea', 'Noidea'), ('action', 'Action'), ('drama', 'Drama'), ('horror', 'Horror'), ('krimi', 'Krimi'), ('thriller', 'Thriller')], default='allgemein', max_length=20),
        ),
    ]
