# Generated by Django 5.0 on 2024-03-06 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videoflixbackend', '0019_alter_video_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='origin',
        ),
    ]
